language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

matrix:
  include:
    - jdk: oraclejdk7
      scala: 2.10.6
    - jdk: oraclejdk7
      scala: 2.11.8
    - jdk: oraclejdk8
      scala: 2.12.0-RC1

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
